services:
  - type: web
    name: laravel-jenkins-render-app
    runtime: docker
    plan: starter
    # Use pre-built Docker image from registry instead of building from source
    image:
      url: docker.io/your-dockerhub-username/laravel-jenkins-render-app:latest
    # Alternative: Build from source (comment out image above and uncomment below)
    # dockerfilePath: ./Dockerfile
    # dockerContext: .
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        fromService:
          type: web
          name: laravel-jenkins-render-app
          property: host
      - key: APP_KEY
        generateValue: true
      - key: LOG_CHANNEL
        value: stderr
      - key: LOG_LEVEL
        value: info
      - key: DB_CONNECTION
        value: sqlite
      - key: DB_DATABASE
        value: /var/www/html/database/database.sqlite
      - key: SESSION_DRIVER
        value: database
      - key: SESSION_LIFETIME
        value: 120
      - key: CACHE_STORE
        value: database
      - key: QUEUE_CONNECTION
        value: database
    buildCommand: echo "Docker build handles the build process"
    startCommand: /usr/local/bin/docker-start.sh
    healthCheckPath: /
    autoDeploy: true
    disk:
      name: laravel-storage
      mountPath: /var/www/html/storage
      sizeGB: 1